name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'story/*'
env:
  CHAPTER_DIR: 'Chapter-3-microservice-extraction'

jobs:
  qodana:
    defaults:
      run:
        working-directory: ${{ env.CHAPTER_DIR }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} 
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: --property, qodana.net.solution=Fitnet.Contracts.sln


